name: habitiurs
description: "App de seguimiento de hábitos con IA integrada"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI y navegación
  cupertino_icons: ^1.0.8
  
  # Manejo de estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Base de datos
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilidades
  intl: ^0.18.1
  
  # Inyección de dependencias
  get_it: ^7.6.4
  
  # HTTP y conectividad para AI Assistant
  http: ^1.1.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Opcional: Si quieres agregar assets para íconos o imágenes
  # assets:
  #   - assets/images/
  #   - assets/icons/