name: habitiurs
description: "App de seguimiento de h치bitos con IA integrada, auth y sincronizaci칩n"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI y navegaci칩n
  cupertino_icons: ^1.0.8
  
  # Manejo de estado
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # Firebase & Auth
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  
  # HTTP y conectividad para AI
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  
  # Utilidades
  intl: ^0.18.1
  
  # Inyecci칩n de dependencias  
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets comentados hasta que los necesites
  # assets:
  #   - assets/images/
  #   - assets/icons/